#!/bin/bash
# rachelpios.sh: a simple script to install Rachelpios
set -o errexit
set -o nounset


# Upgrade System
update(){
    sudo apt-get update
    sudo rpi-update
    sudo apt-get -y dist-upgrade
}

# Install required packages
install_packages(){
    sudo apt-get install -y wget hostapd udhcpd apache2 libapache2-mod-proxy-html libxml2-dev \
     php5-common libapache2-mod-php5 php5-cgi php5 \
     mysql-server mysql-client php5-mysql samba samba-common-bin php5 php-pear php5-xcache php5-gd ffmpeg zip imagemagick
}

# Create wifi hotspot
configure_hotspot(){
    sudo cp udhcpd.conf /etc/udhcpd.conf
    sudo cp udhcpd /etc/default/udhcpd
    sudo cp hostapd /etc/default/hostapd
    sudo cp interfaces /etc/network/interfaces
    sudo cp hostapd.conf /etc/hostapd/hostapd.conf
    sudo sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
    sudo cp sysctl.conf /etc/sysctl.conf
    sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    sudo iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
    sudo iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
    sudo sh -c "iptables-save > /etc/iptables.ipv4.nat"
}


# this script should be able to run if the wifi is not present
check_wifi(){
    if ! ifconfig wlan0; then
        echo "Wifi device not present; skipping."
    else
        sudo ifconfig wlan0 10.10.10.10
        sudo service hostapd start
        sudo service udhcpd start
        sudo update-rc.d hostapd enable
        sudo update-rc.d udhcpd enable
        sh ./ifupdown.sh
    fi
}

# Configure Apache/PHP and MySQL
configure_apache(){
    sudo cp default /etc/apache2/sites-enabled/default
    sudo cp my.cnf /etc/mysql/my.cnf
    sudo a2enmod php5 proxy proxy_html rewrite
    sudo service apache2 restart
    sudo service mysqld restart
    sudo rm -f /var/www/index.html
    sudo cp -r www/* /var/www/
}

#update hostname
setup_hostname(){
    sudo cp hosts /etc/hosts
    sudo cp hostname /etc/hostname
    sudo /etc/init.d/hostname.sh
}

setup_samba(){
    sudo mkdir -p /var/www/local
    sudo chmod 777 /var/www/local
    sudo cp smb.conf /etc/samba/smb.conf
    # sudo cp dhcp.conf /etc/samba/dhcp.conf
    sudo cp gdbcommands /etc/samba/gdbcommands
}

setup_h5ai(){
    sudo wget https://release.larsjung.de/h5ai/h5ai-0.27.0.zip -O /var/www/h5ai-0.27.0.zip
    sudo cd /var/www && unzip h5ai-0.27.0.zip

}

#put realtek drivers in place if needed
setup_realtek(){
    sudo cp hostapd_RTL8188CUS /home/pi/hostapd_RTL
    sudo cp realtek.sh /home/pi/Desktop/realtek.sh
    sudo cp hostapd_realtek.conf /home/pi/hostapd_realtek.conf    
}


#redo wifi enable for good measure
# Need check if this is really needed?
redo_wifi(){
    if ifconfig wlan0; then
        sudo ifconfig wlan0 10.10.10.10
        sudo service hostapd start
        sudo service udhcpd start
        sudo update-rc.d hostapd enable
        sudo update-rc.d udhcpd enable
    fi
}

#install kiwix
# download kiwix-server-0.9-rc2-linux-armv5tejl.tar.bz2
# tar -xjvf above file

echo "Updating the system..."
update
install_packages
configure_hotspot
check_wifi
configure_apache
setup_hostname
setup_samba
setup_h5ai
setup_realtek
redo_wifi

echo "Setup complete..."